import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#004be3",
        "primary-dim": "#0041c8",
        "primary-container": "#819bff",
        "on-primary": "#f2f1ff",
        "on-primary-container": "#001b61",
        "primary-fixed": "#819bff",
        "primary-fixed-dim": "#6c8cff",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#002376",
        "inverse-primary": "#6889ff",
        secondary: "#6c5a00",
        "secondary-dim": "#5e4e00",
        "secondary-container": "#ffd709",
        "secondary-fixed": "#ffd709",
        "secondary-fixed-dim": "#efc900",
        "on-secondary": "#fff2cd",
        "on-secondary-container": "#5b4b00",
        "on-secondary-fixed": "#453900",
        "on-secondary-fixed-variant": "#665500",
        tertiary: "#b30065",
        "tertiary-dim": "#9d0058",
        "tertiary-container": "#ff8db7",
        "tertiary-fixed": "#ff8db7",
        "tertiary-fixed-dim": "#ff74ac",
        "on-tertiary": "#ffeff2",
        "on-tertiary-container": "#650036",
        "on-tertiary-fixed": "#37001b",
        "on-tertiary-fixed-variant": "#750040",
        "highlight-pink": "#F28482",
        error: "#b41340",
        "error-dim": "#a70138",
        "error-container": "#f74b6d",
        "on-error": "#ffefef",
        "on-error-container": "#510017",
        background: "#f8f5ff",
        "on-background": "#2a2b51",
        surface: "#f8f5ff",
        "surface-bright": "#f8f5ff",
        "surface-dim": "#d1d0ff",
        "surface-container": "#e8e6ff",
        "surface-container-low": "#f2efff",
        "surface-container-high": "#e1e0ff",
        "surface-container-highest": "#dbd9ff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dbd9ff",
        "surface-tint": "#004be3",
        "on-surface": "#2a2b51",
        "on-surface-variant": "#575881",
        outline: "#72739e",
        "outline-variant": "#a9a9d7",
        "inverse-surface": "#08082f",
        "inverse-on-surface": "#9999c6",
        "petrol-blue": "#085F7F",
        "petrol-dim": "#064b65",
        "warm-yellow": "#FFD54F",
        "warm-orange": "#F4A261",
      },
      fontFamily: {
        headline: ["Arimo", "sans-serif"],
        display: ["Arimo", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "0px",
        md: "0px",
        sm: "0px",
      },
    },
  },
  plugins: [],
};
export default config;
